### ISSUE TITLE
Parentheses in headers not removed

### ISSUE THREAD

**Issue by bradjc** [pbzweihander/markdown-toc-rs#7]
In this document: https://github.com/tock/tock/blob/master/doc/BluetoothLEStack.md we have a header "Hardware Interface Layer (HIL)". The correct link would be `[Hardware Interface Layer (HIL)](#hardware-interface-layer-hil)`, however markdown-toc is not removing the `()` and is instead generating `[Hardware Interface Layer (HIL)](#hardware-interface-layer-(hil))`.

I'm using version 0.2.0 installed from cargo.

**Comment by cybercoder-naj** [comment]
Can you assign me this issue?

**Comment by pbzweihander** [comment]
Just feel free to open a PR.
