### ISSUE TITLE
Incorrect links when headers have numbers and periods in heading

### ISSUE THREAD

**Issue by bradjc** [pbzweihander/markdown-toc-rs#8]
In this document https://github.com/tock/tock/blob/master/doc/CodeReview.md we have a header `2. Pull Requests`. The expected markdown-toc output is:

```
- [2. Pull Requests](#2-pull-requests)
```

however, md-toc is generating:

```
- [2. Pull Requests](#2.-pull-requests)
```

v0.2.0

**Comment by cybercoder-naj** [comment]
Can you assign me this issue?
